spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
server:
  port: 4003

jwt:
  secret: your_super_secret_key_must_be_32_chars_min
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: false

users:
  service:
    url: http://localhost:4001