version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: rahul2001
      POSTGRES_PASSWORD: Ranaghat@1
    ports:
      - "5433:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U rahul2001"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rahul2711
      MONGO_INITDB_ROOT_PASSWORD: Ranaghat1
    ports:
      - "27018:27017"
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
#      interval: 10s
#      timeout: 5s
#      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 5

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8080:8080"
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
#      interval: 15s
#      timeout: 10s
#      retries: 5

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "4001:4001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: rahul2001
      SPRING_DATASOURCE_PASSWORD: Ranaghat@1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
    depends_on:
      postgres:
        condition: service_healthy
      eureka:
        condition: service_healthy

  activities-service:
    build: ./activities-service
    container_name: activities-service
    ports:
      - "4002:4002"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://rahul2711:Ranaghat1@mongo:27017/activities-db?authSource=admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  recommendation-service:
    build: ./recommendation-service
    container_name: recommendation-service
    ports:
      - "4004:4004"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://rahul2711:Ranaghat1@mongo:27017/fitnessRecommendations-db?authSource=admin
      GEMINI_API_KEY: AIzaSyBIRH02Ha-c3F64rIxzJL8x26XFAd1I-SQ
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "4003:4003"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
    depends_on:
      eureka:
        condition: service_healthy
      users-service:
        condition: service_started
      activities-service:
        condition: service_started
      recommendation-service:
        condition: service_started