spring:
  application:
    name: users-service
  cloud:
    client:
      hostname: fitness-recommendation-project
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never

server:
  port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: false

jwt:
  secret: your-super-secret-key-your-super-secret-key
