spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: rahul2001
    password: Ranaghat@1
  sql:
    init:
      mode: never

server:
  port: 4001