spring:
  application:
    name: recommendation-service
  rabbitmq:
    addresses: amqps://hiorewpd:gUnzN8EgvlPx2QuZoPirHjh4i0B9bshC@lionfish.rmq.cloudamqp.com/hiorewpd
  cloud:
    client:
      hostname: fitness-recommendation-project
  mongodb:
    uri: mongodb+srv://mitrarahul2001_db_user:s0dX5mtHSbx8ekrA@fitness-recommendations.urspfgt.mongodb.net/fitnessRecommendations-db?retryWrites=true&w=majority

server:
  port: 4004

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka
  instance:
    prefer-ip-address: false

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-3-flash-preview

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking