spring:
  application:
    name: activities-service
  cloud:
    client:
      hostname: localhost
  mongodb:
    uri: mongodb://rahul2711:Ranaghat1@localhost:27018/activities-db?authSource=admin
    representation:
      uuid: standard
server:
  port: 4002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: false

